name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 0 * * 1,4'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send a Ping Request
        run: |
          curl -i -X POST "https://vclxksxybwvllshmqlpa.supabase.co/rest/v1/rpc/get_server_time" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json"
